-- MySQL Script generated by MySQL Workbench
-- 08/27/17 09:46:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fazendas_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fazendas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fazendas_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fazendas_db` ;




-- -----------------------------------------------------
-- Table `fazendas_db`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`endereco` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `endereco_rua` VARCHAR(225) NULL COMMENT '',
  `endereco_cep` VARCHAR(255) NULL COMMENT '',
  `endereco_numero` INT NULL COMMENT '',
  `endereco_comp` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`endereco_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`pessoa_fisica` (
  `pessoaFisica_cpf` INT NOT NULL COMMENT '',
  `pessoaFisica_nome` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`pessoaFisica_cpf`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`pessoa_jur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`pessoa_jur` (
  `pessoaJur_cnpj` INT NOT NULL COMMENT '',
  `pessoa_jur_nomeFantasia` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`pessoaJur_cnpj`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoria_nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`categoria_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`img_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`img_produto` (
  `img_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `img_nome` VARCHAR(45) NULL COMMENT '',
  `img_dir` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`img_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`pagseguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`pagseguro` (
  `pagseguro_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pagseguro_tipo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`pagseguro_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`qualificar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`qualificar` (
  `qualificar_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `qualificar_negociacao` VARCHAR(255) NULL COMMENT '',
  `qualificar_anuncio` VARCHAR(255) NULL COMMENT '',
  `qualificar_msg` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`qualificar_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`tipo_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`tipo_anuncio` (
  `tipo_anuncio_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_anuncio_nivel` VARCHAR(255) NULL COMMENT '',
  `tipo_anuncio_valor` FLOAT NULL COMMENT '',
  PRIMARY KEY (`tipo_anuncio_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`anuncio` (
  `anuncio_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `anuncio_titulo` VARCHAR(255) NULL COMMENT '',
  `anuncio_desc` VARCHAR(255) NULL COMMENT '',
  `anuncio_valor` FLOAT NULL COMMENT '',
  `anuncio_datainicial` DATE NULL COMMENT '',
  `anuncio_datafinal` DATE NULL COMMENT '',
  `anuncio_msg` VARCHAR(255) NULL COMMENT '',
  `anuncio_formPag` VARCHAR(255) NULL COMMENT '',
  `categoria_categoria_id` INT NOT NULL COMMENT '',
  `img_produto_img_id` INT NOT NULL COMMENT '',
  `pagseguro_pagseguro_id` INT NOT NULL COMMENT '',
  `qualificar_qualificar_id` INT NOT NULL COMMENT '',
  `tipo_anuncio_tipo_anuncio_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`anuncio_id`, `categoria_categoria_id`, `img_produto_img_id`, `pagseguro_pagseguro_id`, `qualificar_qualificar_id`, `tipo_anuncio_tipo_anuncio_id`)  COMMENT '',
  INDEX `fk_anuncio_categoria1_idx` (`categoria_categoria_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_img_produto1_idx` (`img_produto_img_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_pagseguro1_idx` (`pagseguro_pagseguro_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_qualificar1_idx` (`qualificar_qualificar_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_tipo_anuncio1_idx` (`tipo_anuncio_tipo_anuncio_id` ASC)  COMMENT '',
  CONSTRAINT `fk_anuncio_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `fazendas_db`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_img_produto1`
    FOREIGN KEY (`img_produto_img_id`)
    REFERENCES `fazendas_db`.`img_produto` (`img_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_pagseguro1`
    FOREIGN KEY (`pagseguro_pagseguro_id`)
    REFERENCES `fazendas_db`.`pagseguro` (`pagseguro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_qualificar1`
    FOREIGN KEY (`qualificar_qualificar_id`)
    REFERENCES `fazendas_db`.`qualificar` (`qualificar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipo_anuncio1`
    FOREIGN KEY (`tipo_anuncio_tipo_anuncio_id`)
    REFERENCES `fazendas_db`.`tipo_anuncio` (`tipo_anuncio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fazendas_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fazendas_db`.`usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usu_email` VARCHAR(255) NULL COMMENT '',
  `usu_foneCel` VARCHAR(45) NULL COMMENT '',
  `usu_foneCom` VARCHAR(45) NULL COMMENT '',
  `usu_senha` VARCHAR(255) NULL COMMENT '',
  `endereco_endereco_id` INT NOT NULL COMMENT '',
  `pessoa_fisica_pessoaFisica_cpf` INT NOT NULL COMMENT '',
  `pessoa_jur_pessoaJur_cnpj` INT NOT NULL COMMENT '',
  `anuncio_anuncio_id` INT NOT NULL COMMENT '',
  `anuncio_categoria_categoria_id` INT NOT NULL COMMENT '',
  `anuncio_img_produto_img_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usu_id`, `endereco_endereco_id`, `pessoa_fisica_pessoaFisica_cpf`, `pessoa_jur_pessoaJur_cnpj`, `anuncio_anuncio_id`, `anuncio_categoria_categoria_id`, `anuncio_img_produto_img_id`)  COMMENT '',
  INDEX `fk_usuario_endereco1_idx` (`endereco_endereco_id` ASC)  COMMENT '',
  INDEX `fk_usuario_pessoa_fisica1_idx` (`pessoa_fisica_pessoaFisica_cpf` ASC)  COMMENT '',
  INDEX `fk_usuario_pessoa_jur1_idx` (`pessoa_jur_pessoaJur_cnpj` ASC)  COMMENT '',
  INDEX `fk_usuario_anuncio1_idx` (`anuncio_anuncio_id` ASC, `anuncio_categoria_categoria_id` ASC, `anuncio_img_produto_img_id` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_endereco_id`)
    REFERENCES `fazendas_db`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_pessoaFisica_cpf`)
    REFERENCES `fazendas_db`.`pessoa_fisica` (`pessoaFisica_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pessoa_jur1`
    FOREIGN KEY (`pessoa_jur_pessoaJur_cnpj`)
    REFERENCES `fazendas_db`.`pessoa_jur` (`pessoaJur_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_anuncio1`
    FOREIGN KEY (`anuncio_anuncio_id` , `anuncio_categoria_categoria_id` , `anuncio_img_produto_img_id`)
    REFERENCES `fazendas_db`.`anuncio` (`anuncio_id` , `categoria_categoria_id` , `img_produto_img_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
