-- MySQL Script generated by MySQL Workbench
-- 08/31/17 15:50:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nasfazendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nasfazendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nasfazendas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nasfazendas` ;

-- -----------------------------------------------------
-- Table `nasfazendas`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usu_email` VARCHAR(255) NULL COMMENT '',
  `usu_foneCel` VARCHAR(45) NULL COMMENT '',
  `usu_foneCom` VARCHAR(45) NULL COMMENT '',
  `usu_senha` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`usu_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoria_nome` VARCHAR(45) NULL COMMENT '',
  `categoria_categoria_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`categoria_id`)  COMMENT '',
  INDEX `fk_categoria_categoria1_idx` (`categoria_categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_categoria_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `nasfazendas`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`tipo_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`tipo_anuncio` (
  `tipo_anuncio_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_anuncio_nivel` VARCHAR(255) NULL COMMENT '',
  `tipo_anuncio_valor` FLOAT NULL COMMENT '',
  PRIMARY KEY (`tipo_anuncio_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`anuncio` (
  `anuncio_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `anuncio_titulo` VARCHAR(255) NULL COMMENT '',
  `anuncio_desc` VARCHAR(255) NULL COMMENT '',
  `anuncio_valor` FLOAT NULL COMMENT '',
  `anuncio_datainicial` DATE NULL COMMENT '',
  `anuncio_datafinal` DATE NULL COMMENT '',
  `anuncio_msg` VARCHAR(255) NULL COMMENT '',
  `anuncio_formPag` VARCHAR(255) NULL COMMENT '',
  `usuario_usu_id` INT NOT NULL COMMENT '',
  `categoria_categoria_id` INT NOT NULL COMMENT '',
  `tipo_anuncio_tipo_anuncio_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`anuncio_id`, `usuario_usu_id`)  COMMENT '',
  INDEX `fk_anuncio_usuario1_idx` (`usuario_usu_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_categoria1_idx` (`categoria_categoria_id` ASC)  COMMENT '',
  INDEX `fk_anuncio_tipo_anuncio1_idx` (`tipo_anuncio_tipo_anuncio_id` ASC)  COMMENT '',
  CONSTRAINT `fk_anuncio_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `nasfazendas`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `nasfazendas`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipo_anuncio1`
    FOREIGN KEY (`tipo_anuncio_tipo_anuncio_id`)
    REFERENCES `nasfazendas`.`tipo_anuncio` (`tipo_anuncio_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`img_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`img_produto` (
  `img_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `img_nome` VARCHAR(45) NULL COMMENT '',
  `img_dir` VARCHAR(45) NULL COMMENT '',
  `anuncio_anuncio_id` INT NOT NULL COMMENT '',
  `anuncio_usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`img_id`, `anuncio_anuncio_id`, `anuncio_usuario_usu_id`)  COMMENT '',
  INDEX `fk_img_produto_anuncio1_idx` (`anuncio_anuncio_id` ASC, `anuncio_usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_img_produto_anuncio1`
    FOREIGN KEY (`anuncio_anuncio_id` , `anuncio_usuario_usu_id`)
    REFERENCES `nasfazendas`.`anuncio` (`anuncio_id` , `usuario_usu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`endereco` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `endereco_rua` VARCHAR(225) NULL COMMENT '',
  `endereco_cep` VARCHAR(255) NULL COMMENT '',
  `endereco_numero` INT NULL COMMENT '',
  `endereco_comp` VARCHAR(45) NULL COMMENT '',
  `usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`endereco_id`, `usuario_usu_id`)  COMMENT '',
  INDEX `fk_endereco_usuario1_idx` (`usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `nasfazendas`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`pessoa_fisica` (
  `pessoaFisica_cpf` INT NOT NULL COMMENT '',
  `pessoaFisica_nome` VARCHAR(255) NULL COMMENT '',
  `usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pessoaFisica_cpf`, `usuario_usu_id`)  COMMENT '',
  INDEX `fk_pessoa_fisica_usuario1_idx` (`usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pessoa_fisica_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `nasfazendas`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`pessoa_jur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`pessoa_jur` (
  `pessoaJur_cnpj` INT NOT NULL COMMENT '',
  `pessoa_jur_nomeFantasia` VARCHAR(45) NULL COMMENT '',
  `usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pessoaJur_cnpj`, `usuario_usu_id`)  COMMENT '',
  INDEX `fk_pessoa_jur_usuario1_idx` (`usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pessoa_jur_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `nasfazendas`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`pagseguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`pagseguro` (
  `pagseguro_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pagseguro_tipo` VARCHAR(45) NULL COMMENT '',
  `anuncio_anuncio_id` INT NOT NULL COMMENT '',
  `anuncio_usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pagseguro_id`, `anuncio_anuncio_id`, `anuncio_usuario_usu_id`)  COMMENT '',
  INDEX `fk_pagseguro_anuncio1_idx` (`anuncio_anuncio_id` ASC, `anuncio_usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pagseguro_anuncio1`
    FOREIGN KEY (`anuncio_anuncio_id` , `anuncio_usuario_usu_id`)
    REFERENCES `nasfazendas`.`anuncio` (`anuncio_id` , `usuario_usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nasfazendas`.`qualificar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nasfazendas`.`qualificar` (
  `qualificar_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `qualificar_negociacao` VARCHAR(255) NULL COMMENT '',
  `qualificar_anuncio` VARCHAR(255) NULL COMMENT '',
  `qualificar_msg` VARCHAR(255) NULL COMMENT '',
  `anuncio_anuncio_id` INT NOT NULL COMMENT '',
  `anuncio_usuario_usu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`qualificar_id`, `anuncio_anuncio_id`, `anuncio_usuario_usu_id`)  COMMENT '',
  INDEX `fk_qualificar_anuncio1_idx` (`anuncio_anuncio_id` ASC, `anuncio_usuario_usu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_qualificar_anuncio1`
    FOREIGN KEY (`anuncio_anuncio_id` , `anuncio_usuario_usu_id`)
    REFERENCES `nasfazendas`.`anuncio` (`anuncio_id` , `usuario_usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
